### PR TITLE
(SERVER-648) Merge 2.1.x to master

### PR DESCRIPTION
**Pull request by dankreek**
Since SERVER-647 is still open the unit tests will probably fail.

### CODE REVIEW

**Comment by dankreek** [comment]
Looks like this needs I rebase. I'll get that done asap

**Comment by camlow325** [comment]
fyi - I merged the PR for SERVER-647 this morning - #549.  Not sure if that helps for the current state of this PR?

**Comment by dankreek** [comment]
@camlow325 Shoot.. actually looks like this one can get merged. Let's do it!

**Comment by camlow325** [comment]
:+1:

**Pull request merged**
