### PR TITLE
(SERVER-816) Bump to SSL utils 0.8.1

### PR DESCRIPTION
**Pull request by dankreek**

### CODE REVIEW

**Comment by camlow325** [comment]
:+1:

**Comment by camlow325** [comment]
@nwolfe - Look okay to you?

**Comment by nwolfe** [comment]
:+1:

**Comment by camlow325** [comment]
Crap - I forgot to look at the target branch for this PR.  Can you put up a PR which retargets this at the 1.x branch and also merge that up to the stable branch from there.  Since this is a bug fix, I think we want it on all puppet-server branches, not just master.

**Comment by dankreek** [comment]
!()[http://www.hadafewbeers.com/wp-content/uploads/2014/05/thats-a-paddlin-30027.jpg]

**Pull request merged**
