### PR TITLE
(MAINT) Merge stable up into master

### PR DESCRIPTION
**Pull request by jeffmccune**
Merged using `git merge --no-ff --log -s recursive -X patience -X
diff-algorithm=patience -X ignore-space-change` and resolving the incorrect
automatic resolutions in ps-version in project.clj and a other minor whitespace
errors in gem.clj and friends.

### CODE REVIEW

**Comment by camlow325** [comment]
:+1:

**Comment by jeffmccune** [comment]
We need to run the acceptance tests against this PR before merging as to not lose ground on the effort to get the acceptance tests green.

**Comment by jeffmccune** [comment]
FYI, this merge-up failed at the acceptance level because `puppetserver gem cleanup` is borked due to the infamous `JARS_NO_REQUIRE` patch.  I added dafbe4a602f17878d18bc63618fe02207efa7bc3 to to make this topic branch behave the same as master does without this branch merged into master.

```
        [root@u4e4c61i909s8tj ~]# puppetserver gem cleanup
        ERROR:  Loading command: cleanup (RuntimeError)
                you might need to reinstall the gem which depends on the missing jar
        no such file to load -- org/bouncycastle/bcpkix-jdk15on/1.47/bcpkix-jdk15on-1.47 (LoadError)
        ERROR:  While executing gem ... (NoMethodError)
            undefined method `invoke_with_build_args' for nil:NilClass
```

**Comment by jeffmccune** [comment]
@rlinehan `acceptance/suites/tests` passed with dafbe4a602f17878d18bc63618fe02207efa7bc3

**Pull request merged**
