### PR TITLE
(MAINT) Revert SERVER-262

### PR DESCRIPTION
**Pull request by dankreek**

### CODE REVIEW

**Comment by camlow325** [comment]
:+1: - Not quite sure if some of the acceptance test reverts which would put us back to installing beaker for the gem test will work but we should be able to see that quickly if not.

**Comment by dankreek** [comment]
Updated the acceptance test per @waynr's advice

**Comment by waynr** [comment]
:+1:, I'll be on my toes to watch for failures in the smoke tests

**Comment by jeffmccune** [comment]
Please see https://tickets.puppetlabs.com/browse/SERVER-522 for additional information.

**Pull request merged**
