### PR TITLE
(MAINT) merge 1.x to stable, 2015-08-18

### PR DESCRIPTION
**Pull request by cprice404**
FWIW I believe this is the last change to the OSS code that I will need for metrics stuff, and also the last patch I intended for 1.x at all, so I think maybe we can consider that branch to be in maintenance mode as soon as this gets merged all the way up.

### CODE REVIEW

**Comment by cprice404** [comment]
@camlow325 @KevinCorcoran @fpringvaldsen if this gets merged today, I'll do the merge from stable->master tomorrow.

**Comment by KevinCorcoran** [comment]
:see_no_evil: except for my question above about log messages.

**Comment by camlow325** [comment]
I'd appreciate it if @fpringvaldsen could take a look at this since I didn't review the original PR for this which had been merged to the 1.x branch.

**Comment by fpringvaldsen** [comment]
Also :+1: barring the question about the log messages

**Comment by KevinCorcoran** [comment]
I'm just going to merge this; we can easily add back the logging if we find it to be useful in the future.

**Pull request merged**
