### PR TITLE
(SERVER-1127) Upgrade to TK version w/HUP support

### PR DESCRIPTION
**Pull request by cprice404**
This commit upgrades us to a new version of TK that includes
HUP support.  The internal API for TK's app-context changed
slightly so a few tests and the repl utils needed to be cleaned
up accordingly.

### CODE REVIEW

**Comment by camlow325** [comment]
:+1: once this can be bumped up to a released version of TK - and assuming all of the unit tests will then pass as well.

**Comment by haus** [comment]
this looks good to me. :+1: when tk is available.

**Comment by cprice404** [comment]
SNAPSHOT dep is fixed and this should be ready for final review now.

**Comment by camlow325** [comment]
:+1: Running Travis locally right now as a sanity check.  Will merge if it passes and @haus hasn't objected to anything in the meantime.

**Comment by camlow325** [comment]
Tests pass locally so merging...

**Pull request merged**
