### PR TITLE
(maint) Schemify puppetlabs.puppetserver.testutils

### PR DESCRIPTION
**Pull request by haus**
Previously these test utilities all did not have schemas applied to
them. This commit starts to change that. This introduces schemas to most
of the functions and defines a schema for puppet catalogs and resources.

### CODE REVIEW

**Comment by nathanielksmith** [comment]
:+1: I'm into it. Did you file a bug / find out more about that key thing?

thanks for doing this!

**Comment by haus** [comment]
not yet, planning to still.

**Comment by jpinsonault** [comment]
:+1: thanks for doing this

**Comment by haus** [comment]
for posterity, the schema bug was actually just a special case schema has with keywords in maps.

**Pull request merged**
