### PR TITLE
(MAINT) Merge SERVER-363 changes from stable to master

### PR DESCRIPTION
**Pull request by cprice404**
This commit takes the changes that Nate made in the stable
branch for SERVER-363 (to add lein ezbake support to the
stable branch) and merges them up to the master branch.

### CODE REVIEW

**Comment by nwolfe** [comment]
Building packages and testing locally...

**Comment by nwolfe** [comment]
I verified that I can build packages successfully, but wasn't able to get very far after that due to the AIO paths and all sorts of brokenness that we're in right now.

**Comment by cprice404** [comment]
OK then it sounds like it's probably best to let @jeffmccune decide when this should land?

**Comment by camlow325** [comment]
Yeah, it seems like most of this is going to be undone by @jeffmccune's next PR coming to master -- Gemfile.lock and os-settings references being deleted.  +1 on letting @jeffmccune decide when this should come in.

**Pull request merged**
