### PR TITLE
(SERVER-555) Merge 2.1.x down into master

### PR DESCRIPTION
**Pull request by jeffmccune**
This pull request performs the non-fast-forward merge of 2.1.x into master as
noted in the documented plan of action.  It also updates the README_BRANCHING
document accordingly.

### CODE REVIEW

**Comment by jeffmccune** [comment]
PR comments from #504 have also been addressed here, ready for another pass.

**Comment by camlow325** [comment]
:+1:

**Comment by cprice404** [comment]
+1 with a minor comment on some wording in the branching doc.  I'd be OK merging w/o that being changed though.

We will need to cherry-pick the branching doc changes into `stable`, probably, though.

**Comment by cprice404** [comment]
Oh, I just now saw #504 .

**Comment by jeffmccune** [comment]
> +1 with a minor comment on some wording in the branching doc. 

Addressed in a4d83b4

**Pull request merged**
