### PR TITLE
(SERVER-1079) Implement VersionedCodeService

### PR DESCRIPTION
**Pull request by haus**
This commit implements the trapperkeeper service for
VersionedCodeService which mostly involves implementing current-code-id
for the service.

### CODE REVIEW

**Comment by haus** [comment]
Note: This currently includes SERVER-885 work, as it directly depends on it, but I'll rebase this once that is merged.

**Comment by haus** [comment]
I want to clean up the error messages here still.

**Comment by fpringvaldsen** [comment]
:+1:

**Comment by jpinsonault** [comment]
:+1:

**Pull request merged**
