### PR TITLE
(MAINT) Upgrade clj-http-client and tk-jetty9 dependencies

### PR DESCRIPTION
**Pull request by nwolfe**

### CODE REVIEW

**Comment by nwolfe** [comment]
Blocked on #369 - will rebase when that is merged

**Comment by fpringvaldsen** [comment]
:+1: Pending rebase.

**Comment by nwolfe** [comment]
Rebased

**Comment by jeffmccune** [comment]
Why did we do this?  (I looked in the commit messages and for a ticket, but didn't see anything.)

I ask because I was out on PTO when it went through and I'm trying to keep up to speed.

**Comment by nwolfe** [comment]
@jeffmccune See PR #369 that was linked here.

**Pull request merged**
