### PR TITLE
Mergedown master again

### PR DESCRIPTION
**Pull request by KevinCorcoran**
@camlow325 This PR merges-down `master` into `stable` to pick up your recent changes of the Puppet submodule and such.

### CODE REVIEW

**Comment by KevinCorcoran** [comment]
@camlow325 This now includes your latest changes from master.  It's got 2 merge-down commits but meh.

**Comment by camlow325** [comment]
:+1: Maybe @rlinehan could take a look before we merge?

**Comment by haus** [comment]
:+1: from me. diff looks good. (ps version and ezbake version the only difference)

**Comment by camlow325** [comment]
Since we have two :+1:s I'm going to go ahead and merge.

**Pull request merged**
