### PR TITLE
(MAINT) Update branching README to reflect plans re: 1.0.4

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by KevinCorcoran** [comment]
this is the same as #447  ?

**Comment by cprice404** [comment]
one is stable and one is master, since we can't do merge-ups right now.

**Comment by camlow325** [comment]
:+1: once we decide if "1.0.4" is what we intend to call the next release...

**Comment by rlinehan** [comment]
Rather than hold off on merging until we know for sure whether this release is going to be "1.0.4" or not (because who knows how long that will take or how long it will remain true for) can we just say "1.0.x" and merge it?

**Comment by cprice404** [comment]
Updated to 1.0.8 per discussion with @ahpook .

**Pull request merged**
