### PR TITLE
DOC-1466 part 2/2

### PR DESCRIPTION
**Pull request by nfagerlund**
This is linked with https://github.com/puppetlabs/puppet-docs/pull/423.

### CODE REVIEW

**Comment by fpringvaldsen** [comment]
:+1: once this gets approval from support.

**Comment by nfagerlund** [comment]
This is now OK to merge! I reconsidered the approach though, and left PE-specific instructions in the PE docs. (See linked PR in docs project.)

**Comment by camlow325** [comment]
:+1: @nfagerlund, so you have whatever approval you wanted to get from support for us to merge this?

**Comment by nfagerlund** [comment]
@camlow325 Yes!

**Pull request merged**
