### PR TITLE
(SERVER-1056) Allow unauthenticated access to CRL

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by camlow325** [comment]
:+1: @nwolfe - look okay to you?

**Comment by camlow325** [comment]
@cprice404 - hmm, maybe it would be good to target this at stable and merge up from there since the stable branch has tk-auth support?

**Comment by nwolfe** [comment]
:+1: 

There's few more places where we've got this rule defined:
* https://github.com/puppetlabs/pe-puppetserver/blob/2016.1.x/config/conf.d/auth.conf#L33
* https://github.com/puppetlabs/puppetlabs-puppet_enterprise/blob/2016.1.x/manifests/master/tk_authz.pp#L50

**Comment by cprice404** [comment]
@nwolfe I believe that I already have PRs for both of those?

**Comment by camlow325** [comment]
I talked with @cprice404 about this IRL.  We agreed to let this change just happen on the master branch for now.  We can consider backporting it to the stable branch later if it becomes an issue for users.  So, merging...

**Pull request merged**
