### PR TITLE
Revert Revert (SERVER-415) Update PUPPET_BUILD_VERSION for RE-4141

### PR DESCRIPTION
**Pull request by jeffmccune**
This reverts commit f8c7e2fc47ed52477493a37c9bdb49f556889fb0.

Now that we have the unit tests fixed up with improved semver checking behavior
we can re-update to a PUPPET_BUILD_VERSION that works with RE-4141 and Puppet
4.0.0-rc1

### CODE REVIEW

**Comment by rlinehan** [comment]
When I run `rake spec` on this I get

```
1) Puppet::Server::Master puppet version returns the correct puppet version number
     Failure/Error: master.puppetVersion.should == '3.7.4'
       expected: "3.7.4"
            got: "4.0.0-rc1" (using ==)
```

**Comment by jeffmccune** [comment]
@rlinehan Thanks, I pushed a new commit for SERVER-455 that fixes the `rake spec` tests.

**Comment by nwolfe** [comment]
:+1:

**Comment by camlow325** [comment]
:+1: `rake spec` and `lein test` tests all pass locally for me.  Travis :snail:, so merging...

**Pull request merged**
