### PR TITLE
(SERVER-510) Copy 070_InstallCACerts pre-suite step from puppet

### PR DESCRIPTION
**Pull request by jeffmccune**
If this pull request is merged into master in conjunction with #459 then the full acceptance suite is expected to behave as indicated by the [puppet-server (aio) 25:  Full Acceptance Test Suite build #34](https://jenkins.puppetlabs.com/view/Puppet%20Server/view/aio/job/experimental_puppet-server_integration-system_full-aio/34/)

Without this patch the full acceptance tests are failing on windows agents with
the following error:

    #<Beaker::Host::CommandFailure: Host 'wpq3xgx1ug1q866.delivery.puppetlabs.net' exited with 1 running:
    cmd.exe /c puppet module install pmtacceptance-nginx
    Last 10 lines of output were:
           Notice: Preparing to install into C:/ProgramData/PuppetLabs/code/environments/production/modules ...
           Notice: Downloading from https://forgeapi.puppetlabs.com ...
           Error: Could not connect via HTTPS to https://forgeapi.puppetlabs.com
             Unable to verify the SSL certificate
               The certificate may not be signed by a valid CA
               The CA bundle included with OpenSSL may not be valid or up to date>

This issue is tracked in
[PUP-3442](https://tickets.puppetlabs.com/browse/PUP-3442) and
[PUP-3450](https://tickets.puppetlabs.com/browse/PUP-3450).

This patch works around the problem in the same way that puppet core works
around the problem, by copying a CA bundle onto the windows system under test
that works with the forgeapi being tested.

### CODE REVIEW

**Comment by jeffmccune** [comment]
This  patch looks like it will get windows fully green in smoke tests and full acceptance tests if merged into master after #459 is merged into master.

This is based on the results of [puppet-server (aio) 25:  Full Acceptance Test Suite build #34](https://jenkins.puppetlabs.com/view/Puppet%20Server/view/aio/job/experimental_puppet-server_integration-system_full-aio/34/)

**Comment by rlinehan** [comment]
I dislike the amount of duplication between the puppet-server acceptance test setup and the puppet acceptance test setup, but that's a much bigger issue that's probably not solveable in the short term.

:+1:

**Comment by jeffmccune** [comment]
@rlinehan I agree 100%, both in the dislike and the opinion that now probably isn't the right time to try and DRY up the duplication of pre-suite code.

**Comment by dankreek** [comment]
:+1:  Looks good.

**Pull request merged**
