### PR TITLE
(MAINT) Bump Ruby puppet version

### PR DESCRIPTION
**Pull request by dankreek**
This is needed to maintain acceptance test parity with the new version
of MRI Puppet.

### CODE REVIEW

**Comment by rlinehan** [comment]
This looks like the SHA where the PUPPETVERSION was bumped to 3.7.4, so assuming that's what we want, :+1:.

**Comment by camlow325** [comment]
I think Puppet 3.7.4 is used with a newer version of Facter, too, so we probably should bump our submodule for that also.  I think the right version is 2.4.0 - GIT SHA 8ff4fa5e0251aaa1b3fea1e2e308a34b2ffe6027.

**Comment by dankreek** [comment]
@camlow325 Bumped facter up to 2.4.0

**Comment by camlow325** [comment]
I think you'll also need to update the "returns the correct puppet version number" test in .../spec/puppet-server-lib/puppet/jvm/master_spec.rb from '3.7.3' to '3.7.4'.

**Comment by dankreek** [comment]
I dang, I only ran 2 different tests suites before submitting this

**Comment by camlow325** [comment]
:+1:

**Pull request merged**
