### PR TITLE
(MAINT) Add comments explaining flush-instance-agent

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by camlow325** [comment]
:+1:, although might be good to put this in the 1.x branch and merge up from there?

**Comment by haus** [comment]
also :+1:

**Comment by fpringvaldsen** [comment]
Are we retargeting this at the 1.x branch and merging up, or should I go ahead and merge this into master?

**Comment by cprice404** [comment]
I'm not planning on targeting anything besides bugfixes at 1.x from now on, so, I don't really think it's worth the effort, but I'll do it if anyone feels strongly about it.

**Comment by camlow325** [comment]
Fine with me.  :ship:

**Pull request merged**
