### PR TITLE
(maint) Merge stable into master

### PR DESCRIPTION
**Pull request by haus**

### CODE REVIEW

**Comment by haus** [comment]
Looks like this mergeup is mostly:
- docs
- move p-a dependency to 1.3.0 or higher
- fix for jruby pool return/release
- update p-a deps to 1.3.2 for testing

**Comment by haus** [comment]
Also, the main goal of this PR is to get http://jenkins-enterprise.delivery.puppetlabs.net/job/enterprise_puppet-server_integration-system_no-conditional_smoke-master/ green.

**Comment by erikPrime** [comment]
:+1:

**Comment by erikPrime** [comment]
"It's easier to ask forgiveness than to acquire permission."  Merged.  We need to get this through.  If its bad we can revert it.  Waited long enough.

**Pull request merged**
