### PR TITLE
(FOR REVIEW) (SERVER-475) add status service

### PR DESCRIPTION
**Pull request by cprice404**
This isn't ready for merge yet; still waiting for things to stabilize a bit in the status service itself.  Thought it might be worth posting now, though, so people could see roughly what the interaction will look like.

### CODE REVIEW

**Comment by fpringvaldsen** [comment]
:see_no_evil: This is looking great so far!

**Comment by cprice404** [comment]
This is updated to work with the latest status service code.  Blocked on https://github.com/puppetlabs/trapperkeeper-status/pull/11

**Comment by nwolfe** [comment]
@cprice404 Looks like https://github.com/puppetlabs/trapperkeeper-status/pull/11 has been merged.  Is this unblocked now?

Also needs a rebase.

**Comment by cprice404** [comment]
@nwolfe  thanks for the ping; closing this until we have clarity around what version of Puppet Server is going into Shallow Gravy, because I don't think this will be fully ready for release by then.

**Pull request closed without merging**
